# image de base
FROM node:22-alpine AS base

WORKDIR /app
COPY . .
RUN npm install

# image de developpement
FROM base AS development
EXPOSE 8080
CMD ["npm", "run", "dev"]

# Production stage: Build and serve with Nginx
FROM node:18 AS build
WORKDIR /app
COPY . .
COPY --from=base /app/node_modules ./node_modules
RUN npm run build

FROM nginx:latest AS production
WORKDIR /usr/share/nginx/html
RUN rm -rf ./*
COPY --from=build /app/dist .
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]