services:
  frontend:
    container_name: frontend
    build: 
      context: ./frontend
      target: production
    env_file:
        - ./frontend/.env.production
    ports:
      - "8081:80" # changement de port pour nginx sur port 80
    networks:
      - app-network
    
  auth-service:
    container_name: auth-service
    build: 
      context: ./services/auth-service
      target: production
    env_file:
      - ./services/auth-service/.env.production

  product-service:
    build: 
      context: ./services/product-service
      target: production
    env_file:
      - ./services/product-service/.env
    volumes:
      - ./scripts/init-products.sh:/app/init-products.sh

networks:
  app-network:
    driver: bridge