services:
  frontend:
    build:
      target: development
    ports:
      - "8080:8080" # Vue Dev Server
    volumes:
      - ./frontend:/app
      - /app/node_modules # Prevent node_modules from being overwritten

  auth-service:
    build: 
      target: development
    env_file:
      - ./services/auth-service/.env
    volumes:
      - ./services/auth-service:/app
      - /app/node_modules # Prevent node_modules from being overwritten

  order-service:
      build: 
        target: development
      env_file:
        - ./services/order-service/.env
      volumes:
        - ./services/order-service:/app
        - /app/node_modules

  product-service:
    build: 
      target: development
    env_file:
      - ./services/product-service/.env
    volumes:
      - ./services/product-service:/app
      - /app/node_modules
      - ./scripts/init-products.sh:/app/init-products.sh
    