services:
  frontend:
    container_name: frontend
    build: 
      context: ./frontend
      target: production
    environment:
      VITE_PRODUCT_SERVICE_URL: ${VITE_PRODUCT_SERVICE_URL}
      VITE_AUTH_SERVICE_URL: ${VITE_AUTH_SERVICE_URL}
      VITE_ORDER_SERVICE_URL: ${VITE_ORDER_SERVICE_URL}
      JWT_SECRET: ${JWT_SECRET}
      MONGODB_URI: ${MONGODB_URI}
    ports:
      - "8081:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge