FROM node:22-alpine AS base

WORKDIR /app
COPY . .
RUN npm install

FROM base AS development
EXPOSE 3003
CMD ["npm", "run", "dev"]

FROM node:18 AS production
WORKDIR /app
COPY . .
COPY --from=base /app/node_modules ./node_modules
CMD ["npm", "start"]