FROM node:22-alpine AS base

WORKDIR /app
COPY . .
RUN npm install
RUN apk add --no-cache wget \
    && wget -O /usr/local/bin/gosu "https://github.com/tianon/gosu/releases/download/1.16/gosu-amd64" \
    && chmod +x /usr/local/bin/gosu \
    && addgroup -S appgroup && adduser -S appuser -G appgroup \
    && chown -R appuser:appgroup /app

FROM base AS development
USER appuser
EXPOSE 3003
CMD ["npm", "run", "dev"]

FROM node:18 AS production
WORKDIR /app
COPY . .
COPY --from=base /app/node_modules ./node_modules
RUN apt-get update && apt-get upgrade -y && apt-get install -y wget \
    && wget -O /usr/local/bin/gosu "https://github.com/tianon/gosu/releases/download/1.16/gosu-amd64" \
    && chmod +x /usr/local/bin/gosu \
    && addgroup --system appgroup \
    && adduser --system --ingroup appgroup appuser \
    && chown -R appuser:appgroup /app
USER appuser
CMD ["npm", "start"]