FROM node:22-alpine AS base

WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install
COPY . .

# lance npm run dev avec nodemon pour env developement
FROM base AS development
CMD ["npm", "run", "dev"]

# lance npm run start avec node pour env production
FROM base AS production
CMD ["npm", "run", "start"]