FROM node:22-alpine AS base

LABEL org.opencontainers.image.source="https://github.com/Pyracantharia/Docker4IW3"

WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install
COPY . .
RUN apk add --no-cache wget \
    && wget -O /usr/local/bin/gosu "https://github.com/tianon/gosu/releases/download/1.16/gosu-amd64" \
    && chmod +x /usr/local/bin/gosu \
    && addgroup -S appgroup && adduser -S appuser -G appgroup \
    && chown -R appuser:appgroup /app

# lance npm run dev avec nodemon pour env developement
FROM base AS development
USER appuser
CMD ["npm", "run", "dev"]

# lance npm run start avec node pour env production
FROM base AS production
USER appuser
CMD ["npm", "run", "start"]