name: Test Project

on:
  pull_request:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          
      - run: npm install
        working-directory: ./frontend/
      - run: npm install
        working-directory: ./services/auth-service/
      - run: npm install
        working-directory: ./services/order-service/
      - run: npm install
        working-directory: ./services/product-service/

      - run: npm test
        working-directory: ./frontend/
      - run: npm test
        working-directory: ./services/auth-service/
      - run: npm test
        working-directory: ./services/order-service/
      - run: npm test
        working-directory: ./services/product-service/

      - run: docker compose up --build -d
